version: '3.8'
services:
  backend-1:
    build: ./backend
    ports:
      - "5001:5000"

  backend-2:
    build: ./backend
    ports:
      - "5002:5000"
  backend-3:
    build: ./backend
    ports:
      - "5003:5000"
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend-1
      - backend-2
      - backend-3
