name: SSH into Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Azure VM and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Running commands on Azure VM..."
            # Add your commands here
            ls -l
            sudo apt-get update

      # Step 4: Clone repository on Azure VM and update it with the latest changes from GitHub
      - name: Clone Repository on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          sudo apt update
          sudo apt install -y git
          git clone https://github.com/abhixsh/ClimaX
          git pull origin main
          ls -a
          EOF
