name: SSH into Azure VM

on:
  push:
    branches: [ master ]  # Change this if you're using a different branch (e.g., 'main')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Azure VM and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure this is the correct private key stored in GitHub Secrets
          script: |
            echo "Running commands on Azure VM..."
            ls -l
            sudo apt-get update
